// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

#ifndef CXX_OPTIONS_HXX
#define CXX_OPTIONS_HXX

// Begin prologue.
//
//
// End prologue.

#include <cstddef>

#include <types.hxx>

#include <options.hxx>

namespace CXX
{
  class options: public ::options
  {
    public:
    // Option accessors and modifiers.
    //
    const NarrowString&
    output_dir () const;

    NarrowString&
    output_dir ();

    void
    output_dir (const NarrowString&);

    const NarrowString&
    char_encoding () const;

    NarrowString&
    char_encoding ();

    void
    char_encoding (const NarrowString&);

    const bool&
    no_stl () const;

    bool&
    no_stl ();

    void
    no_stl (const bool&);

    const bool&
    no_iostream () const;

    bool&
    no_iostream ();

    void
    no_iostream (const bool&);

    const bool&
    no_exceptions () const;

    bool&
    no_exceptions ();

    void
    no_exceptions (const bool&);

    const bool&
    no_long_long () const;

    bool&
    no_long_long ();

    void
    no_long_long (const bool&);

    const bool&
    custom_allocator () const;

    bool&
    custom_allocator ();

    void
    custom_allocator (const bool&);

    const bool&
    generate_inline () const;

    bool&
    generate_inline ();

    void
    generate_inline (const bool&);

    const bool&
    suppress_reset () const;

    bool&
    suppress_reset ();

    void
    suppress_reset (const bool&);

    const bool&
    generate_xml_schema () const;

    bool&
    generate_xml_schema ();

    void
    generate_xml_schema (const bool&);

    const NarrowString&
    extern_xml_schema () const;

    NarrowString&
    extern_xml_schema ();

    void
    extern_xml_schema (const NarrowString&);

    const NarrowStrings&
    namespace_map () const;

    NarrowStrings&
    namespace_map ();

    void
    namespace_map (const NarrowStrings&);

    const NarrowStrings&
    namespace_regex () const;

    NarrowStrings&
    namespace_regex ();

    void
    namespace_regex (const NarrowStrings&);

    const bool&
    namespace_regex_trace () const;

    bool&
    namespace_regex_trace ();

    void
    namespace_regex_trace (const bool&);

    const NarrowStrings&
    reserved_name () const;

    NarrowStrings&
    reserved_name ();

    void
    reserved_name (const NarrowStrings&);

    const bool&
    include_with_brackets () const;

    bool&
    include_with_brackets ();

    void
    include_with_brackets (const bool&);

    const NarrowString&
    include_prefix () const;

    NarrowString&
    include_prefix ();

    void
    include_prefix (const NarrowString&);

    const NarrowStrings&
    include_regex () const;

    NarrowStrings&
    include_regex ();

    void
    include_regex (const NarrowStrings&);

    const bool&
    include_regex_trace () const;

    bool&
    include_regex_trace ();

    void
    include_regex_trace (const bool&);

    const NarrowString&
    guard_prefix () const;

    NarrowString&
    guard_prefix ();

    void
    guard_prefix (const NarrowString&);

    const NarrowString&
    hxx_suffix () const;

    NarrowString&
    hxx_suffix ();

    void
    hxx_suffix (const NarrowString&);

    const NarrowString&
    ixx_suffix () const;

    NarrowString&
    ixx_suffix ();

    void
    ixx_suffix (const NarrowString&);

    const NarrowString&
    cxx_suffix () const;

    NarrowString&
    cxx_suffix ();

    void
    cxx_suffix (const NarrowString&);

    const NarrowString&
    fwd_suffix () const;

    NarrowString&
    fwd_suffix ();

    void
    fwd_suffix (const NarrowString&);

    const NarrowString&
    hxx_regex () const;

    NarrowString&
    hxx_regex ();

    void
    hxx_regex (const NarrowString&);

    const NarrowString&
    ixx_regex () const;

    NarrowString&
    ixx_regex ();

    void
    ixx_regex (const NarrowString&);

    const NarrowString&
    cxx_regex () const;

    NarrowString&
    cxx_regex ();

    void
    cxx_regex (const NarrowString&);

    const NarrowString&
    fwd_regex () const;

    NarrowString&
    fwd_regex ();

    void
    fwd_regex (const NarrowString&);

    const NarrowStrings&
    hxx_prologue () const;

    NarrowStrings&
    hxx_prologue ();

    void
    hxx_prologue (const NarrowStrings&);

    const NarrowStrings&
    ixx_prologue () const;

    NarrowStrings&
    ixx_prologue ();

    void
    ixx_prologue (const NarrowStrings&);

    const NarrowStrings&
    cxx_prologue () const;

    NarrowStrings&
    cxx_prologue ();

    void
    cxx_prologue (const NarrowStrings&);

    const NarrowStrings&
    fwd_prologue () const;

    NarrowStrings&
    fwd_prologue ();

    void
    fwd_prologue (const NarrowStrings&);

    const NarrowStrings&
    prologue () const;

    NarrowStrings&
    prologue ();

    void
    prologue (const NarrowStrings&);

    const NarrowStrings&
    hxx_epilogue () const;

    NarrowStrings&
    hxx_epilogue ();

    void
    hxx_epilogue (const NarrowStrings&);

    const NarrowStrings&
    ixx_epilogue () const;

    NarrowStrings&
    ixx_epilogue ();

    void
    ixx_epilogue (const NarrowStrings&);

    const NarrowStrings&
    cxx_epilogue () const;

    NarrowStrings&
    cxx_epilogue ();

    void
    cxx_epilogue (const NarrowStrings&);

    const NarrowStrings&
    fwd_epilogue () const;

    NarrowStrings&
    fwd_epilogue ();

    void
    fwd_epilogue (const NarrowStrings&);

    const NarrowStrings&
    epilogue () const;

    NarrowStrings&
    epilogue ();

    void
    epilogue (const NarrowStrings&);

    const NarrowString&
    hxx_prologue_file () const;

    NarrowString&
    hxx_prologue_file ();

    void
    hxx_prologue_file (const NarrowString&);

    const NarrowString&
    ixx_prologue_file () const;

    NarrowString&
    ixx_prologue_file ();

    void
    ixx_prologue_file (const NarrowString&);

    const NarrowString&
    cxx_prologue_file () const;

    NarrowString&
    cxx_prologue_file ();

    void
    cxx_prologue_file (const NarrowString&);

    const NarrowString&
    fwd_prologue_file () const;

    NarrowString&
    fwd_prologue_file ();

    void
    fwd_prologue_file (const NarrowString&);

    const NarrowString&
    prologue_file () const;

    NarrowString&
    prologue_file ();

    void
    prologue_file (const NarrowString&);

    const NarrowString&
    hxx_epilogue_file () const;

    NarrowString&
    hxx_epilogue_file ();

    void
    hxx_epilogue_file (const NarrowString&);

    const NarrowString&
    ixx_epilogue_file () const;

    NarrowString&
    ixx_epilogue_file ();

    void
    ixx_epilogue_file (const NarrowString&);

    const NarrowString&
    cxx_epilogue_file () const;

    NarrowString&
    cxx_epilogue_file ();

    void
    cxx_epilogue_file (const NarrowString&);

    const NarrowString&
    fwd_epilogue_file () const;

    NarrowString&
    fwd_epilogue_file ();

    void
    fwd_epilogue_file (const NarrowString&);

    const NarrowString&
    epilogue_file () const;

    NarrowString&
    epilogue_file ();

    void
    epilogue_file (const NarrowString&);

    // Print usage information.
    //
    static ::cli::usage_para
    print_usage (::std::wostream&,
                 ::cli::usage_para = ::cli::usage_para::none);

    // Implementation details.
    //
    protected:
    options ();

    bool
    _parse (const char*, ::cli::scanner&);

    public:
    NarrowString output_dir_;
    NarrowString char_encoding_;
    bool no_stl_;
    bool no_iostream_;
    bool no_exceptions_;
    bool no_long_long_;
    bool custom_allocator_;
    bool generate_inline_;
    bool suppress_reset_;
    bool generate_xml_schema_;
    NarrowString extern_xml_schema_;
    NarrowStrings namespace_map_;
    NarrowStrings namespace_regex_;
    bool namespace_regex_trace_;
    NarrowStrings reserved_name_;
    bool include_with_brackets_;
    NarrowString include_prefix_;
    NarrowStrings include_regex_;
    bool include_regex_trace_;
    NarrowString guard_prefix_;
    NarrowString hxx_suffix_;
    NarrowString ixx_suffix_;
    NarrowString cxx_suffix_;
    NarrowString fwd_suffix_;
    NarrowString hxx_regex_;
    NarrowString ixx_regex_;
    NarrowString cxx_regex_;
    NarrowString fwd_regex_;
    NarrowStrings hxx_prologue_;
    NarrowStrings ixx_prologue_;
    NarrowStrings cxx_prologue_;
    NarrowStrings fwd_prologue_;
    NarrowStrings prologue_;
    NarrowStrings hxx_epilogue_;
    NarrowStrings ixx_epilogue_;
    NarrowStrings cxx_epilogue_;
    NarrowStrings fwd_epilogue_;
    NarrowStrings epilogue_;
    NarrowString hxx_prologue_file_;
    NarrowString ixx_prologue_file_;
    NarrowString cxx_prologue_file_;
    NarrowString fwd_prologue_file_;
    NarrowString prologue_file_;
    NarrowString hxx_epilogue_file_;
    NarrowString ixx_epilogue_file_;
    NarrowString cxx_epilogue_file_;
    NarrowString fwd_epilogue_file_;
    NarrowString epilogue_file_;
  };
}

#include <cxx/options.ixx>

// Begin epilogue.
//
//
// End epilogue.

#endif // CXX_OPTIONS_HXX
